const api='/api/tasks'; let tasks=[]; const $=s=>document.querySelector(s);
const formatDate=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'';
const localValue=value=>value?value.replace('Z','').slice(0,16):'';
async function request(url,options={}){const res=await fetch(url,{headers:{'Content-Type':'application/json'},...options});if(!res.ok)throw new Error((await res.json()).error||'Something went wrong');return res.json()}
async function load(){tasks=await request(api);render();checkReminders()}
function render(){const filter=$('#filter').value;const list=$('#taskList');const visible=tasks.filter(t=>filter==='all'||filter==='active'?!t.completed:t.completed);list.innerHTML='';$('#openCount').textContent=tasks.filter(t=>!t.completed).length;const today=new Date().toDateString();$('#todayCount').textContent=tasks.filter(t=>!t.completed&&t.dueAt&&new Date(t.dueAt).toDateString()===today).length;$('#doneCount').textContent=tasks.filter(t=>t.completed).length;if(!visible.length){list.innerHTML='<p class="empty">Nothing here yet. Add one good next step.</p>';return}const template=$('#taskTemplate');visible.forEach(t=>{const node=template.content.cloneNode(true);const article=node.querySelector('.task');article.classList.toggle('completed',t.completed);node.querySelector('h3').textContent=t.title;node.querySelector('.notes').textContent=t.notes;node.querySelector('.notes').hidden=!t.notes;const cat=node.querySelector('.category');cat.textContent=t.category;const priority=node.querySelector('.priority');priority.textContent=t.priority;priority.classList.add(t.priority);const due=node.querySelector('.due');due.textContent=t.dueAt?'Due '+formatDate(t.dueAt):'No due date';node.querySelector('.check').onclick=()=>update(t.id,{completed:!t.completed});node.querySelector('.delete').onclick=()=>{if(confirm('Delete this task?'))remove(t.id)};list.append(node)})}
async function update(id,data){await request(`${api}/${id}`,{method:'PATCH',body:JSON.stringify(data)});await load()}
async function remove(id){await request(`${api}/${id}`,{method:'DELETE'});await load()}
$('#taskForm').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);const data=Object.fromEntries(form);data.dueAt=localValue(data.dueAt);data.remindAt=localValue(data.remindAt);try{await request(api,{method:'POST',body:JSON.stringify(data)});e.target.reset();$('#formError').textContent='';await load()}catch(err){$('#formError').textContent=err.message}}
$('#filter').onchange=render;$('#notify').onclick=async()=>{if(!('Notification'in window))return alert('This browser does not support notifications.');const permission=await Notification.requestPermission();$('#notify').textContent=permission==='granted'?'Reminders enabled':'Reminders blocked'};
function checkReminders(){if(Notification.permission!=='granted')return;const seen=JSON.parse(localStorage.taskPilotNotified||'{}');const current=Date.now();tasks.filter(t=>!t.completed&&t.remindAt&&new Date(t.remindAt).getTime()<=current&&!seen[t.id]).forEach(t=>{new Notification('TaskPilot reminder',{body:t.title});seen[t.id]=true});localStorage.taskPilotNotified=JSON.stringify(seen)}
load().catch(err=>$('#taskList').innerHTML=`<p class="empty">Could not load tasks: ${err.message}</p>`);setInterval(()=>load().catch(()=>{}),60000);
